---
###############################################################################
################################# INSTALL #####################################
###############################################################################

- name: create the container base directory
  file:
    path: "{{ container_prefix }}"
    state: directory
    mode: 0755
    owner: "{{container_user}}"
    group: "{{container_group}}"

- name: create the conf paths
  file:
    path: "{{ container_conf_dir }}"
    state: directory
    mode: 0755
    owner: "{{container_user}}"
    group: "{{container_group}}"

- name: create the data paths
  file:
    path: "{{ container_prefix }}/data"
    state: directory
    mode: 0755
    owner: "{{container_user}}"
    group: "{{container_group}}"

- name: create the log paths
  file:
    path: "{{ container_prefix }}/log"
    state: directory
    mode: 0755
    owner: "{{container_user}}"
    group: "{{container_group}}"

- name: Add envfile for {{service_name}}
  template:
    src: container.envfile.j2
    dest: "{{container_env_file}}"
    mode: 0600
    owner: "{{container_user}}"
    group: "{{container_group}}"
